#!/usr/bin/env -S deno run -q --ext=ts

import { createRPC } from "https://deno.land/x/deno_json_rpc@v1.0.0/src/rpc_two.ts";
import { createOmeggaIO } from "./omegga_io.ts";

import documentation from "./doc.json" assert { type: "json" }; // witness the beauty of deno

const rpc = createRPC(createOmeggaIO());

rpc.onRequest("init", () => ({ registeredCommands: [] }));

rpc.onNotification("start", () => {
  console.log(`${documentation.name} started!`);

  const intervalId = setInterval(() => {
    console.log(`Hello from ${documentation.name}!`);
  }, 1000);

  rpc.onRequest("stop", () => {
    console.log(`${documentation.name} stopped!`);
    clearInterval(intervalId);
  });
});

rpc.start();
